apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alert-rules
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:

  - name: node-alerts
    rules:

    - alert: HighCPUUsage
      expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[5m])) * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        description: "High CPU usage detected (>80%) on node {{ $labels.instance }}"
        summary: "Node CPU high"

    - alert: HighMemoryUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        description: "High Memory usage detected (>80%) on node {{ $labels.instance }}"
        summary: "Node memory high"

    - alert: NodeDiskRunningOut
      expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) 
            / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "Disk usage >85% on {{ $labels.instance }}"
        summary: "Node disk almost full"

    - alert: NodeDown
      expr: kube_node_status_condition{condition="Ready",status="true"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        description: "Node {{ $labels.node }} is down"
        summary: "Node down"

  - name: pod-alerts
    rules:

    - alert: PodCrashLooping
      expr: kube_pod_container_status_restarts_total > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "Pod {{ $labels.pod }} in {{ $labels.namespace }} is restarting too often"
        summary: "Pod CrashLoopBackOff"

    - alert: PodNotReady
      expr: kube_pod_status_ready{condition="true"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        description: "Pod {{ $labels.pod }} is not Ready"
        summary: "Pod Unavailable"

    - alert: ServiceDown
      expr: kube_service_info == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        description: "Service {{ $labels.service }} seems down"
        summary: "Service down"

  - name: api-latency-alerts
    rules:
    - alert: HighAPILatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "High API latency detected"
        summary: "API latency > 500ms"
