apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"monitoring","meta.helm.sh/release-namespace":"monitoring"},"creationTimestamp":"2025-12-02T18:27:49Z","labels":{"app.kubernetes.io/instance":"monitoring","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"12.3.0","helm.sh/chart":"grafana-10.3.0"},"name":"monitoring-grafana","namespace":"monitoring","resourceVersion":"61829","uid":"629e5a78-eec2-47bc-99c0-920cb0007f3e"},"spec":{"clusterIP":"172.20.125.197","clusterIPs":["172.20.125.197"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http-web","port":80,"protocol":"TCP","targetPort":"grafana"}],"selector":{"app.kubernetes.io/instance":"monitoring","app.kubernetes.io/name":"grafana"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-02T18:27:49Z"
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.0
    helm.sh/chart: grafana-10.3.0
  name: monitoring-grafana
  namespace: monitoring
  resourceVersion: "69841"
  uid: 629e5a78-eec2-47bc-99c0-920cb0007f3e
spec:
  clusterIP: 172.20.125.197
  clusterIPs:
  - 172.20.125.197
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    nodePort: 32187
    port: 80
    protocol: TCP
    targetPort: grafana
  selector:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
